### ISSUE TITLE
Limit menu's description to 140 letters

### ISSUE THREAD

**Issue by TorIsHere** [gobbl/adam#1]
"Reading" ain't nobody got time for that.

Limit menu's description to 140 letters. Limiting the description for the food's menu, force restaurants/shop owner to write only essential parts.

**Comment by kelvintaywl** [comment]
@iToRCoding 

sounds good to me!

is there already implemented on Adam? if not, i"ve assigned it as a chore and of 'p 0' priority (meaning: **high** priority) to get it done. In any case will update Snakebite to cut off descriptions to 140 letters too.

**Comment by iToRCoding** [comment]
:+1:

**Comment by kelvintaywl** [comment]
closing this as this is managed by server end

**Comment by TorIsHere** [comment]
:beers:
